/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ElMeaage: typeof import('element-plus/es').ElMeaage
  const ElMessage: typeof import('element-plus/es').ElMessage
}
